const DOUBLE_SQUARE = 2
const TALL_OCTAGON = 1.924
const TALL_HEXAGON = 1.866
const OCTAGON = 1.848
const HEXAGON = 1.732
const TALL_PENTAGON = 1.701
const GOLDEN_SECTION = 1.618
const PENTAGON = 1.539
const SHORT_PENTAGON = 1.376
const TALL_HALF_OCTOGON = 1.307
const HALF_OCTOGON = 1.207
const TRUNCATED_PENTAGON = 1.175
const TURNED_HEXAGON = 1.155
const TALL_CROSS_OCTAGON = 1.082
const TURNED_PENTAGON = 1.051
const SQUARE = 1
const BROAD_PENTAGON = 0.951
const BROAD_CROSS_OCTAGON = 0.924
const BROAD_HEXAGON = 0.866
const FULL_CROSS_HEXAGON = 0.829
const ISO = 1.414
const OCTAVE = 2
const MAJOR_SEVENTH = 1.875
const MINOR_SEVENTH = 1.778
const MAJOR_SIXTH = 1.667
const MINOR_SIXTH = 1.6
const FIFTH = 1.5
const DIMINISHED_FIFTH = 1.414
const FOURTH = 1.333
const MAJOR_THIRD = 1.25
const MINOR_THIRD = 1.2
const MAJOR_SECOND = 1.125
const MINOR_SECOND = 1.067
const UNISON = 1

const SCALE = Object.freeze({
  DOUBLE_SQUARE,
  TALL_OCTAGON,
  TALL_HEXAGON,
  OCTAGON,
  HEXAGON,
  TALL_PENTAGON,
  GOLDEN_SECTION,
  PENTAGON,
  SHORT_PENTAGON,
  TALL_HALF_OCTOGON,
  HALF_OCTOGON,
  TRUNCATED_PENTAGON,
  TURNED_HEXAGON,
  TALL_CROSS_OCTAGON,
  TURNED_PENTAGON,
  SQUARE,
  BROAD_PENTAGON,
  BROAD_CROSS_OCTAGON,
  BROAD_HEXAGON,
  FULL_CROSS_HEXAGON,
  ISO,
  OCTAVE,
  MAJOR_SEVENTH,
  MINOR_SEVENTH,
  MAJOR_SIXTH,
  MINOR_SIXTH,
  FIFTH,
  DIMINISHED_FIFTH,
  FOURTH,
  MAJOR_THIRD,
  MINOR_THIRD,
  MAJOR_SECOND,
  MINOR_SECOND,
  UNISON,
  // Aliases
  GOLDEN_RATIO: GOLDEN_SECTION,
  GOLDEN_MEAN: GOLDEN_SECTION,
  AUGMENTED_FOURTH: DIMINISHED_FIFTH,
})

export default SCALE
